name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2 
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x'
    - name: Install dependencies
      run: |
        dotnet restore DemoContentBuilder
        dotnet restore Demos
    - name: Build
      run: |
        dotnet build DemoContentBuilder --configuration Release --no-restore /p:Platform=x64
        dotnet build Demos --configuration Release --no-restore
    - name: Test
      run: dotnet test DemoTests -c Release --verbosity normal
    - name: Publish
      run: |
        dotnet nuget add source "https://nuget.pkg.github.com/bepu/index.json" --name "github" --username "rossnordby" --password "${{secrets.GITHUB_TOKEN}}"
        dotnet pack "BepuPhysics" -c Release
        dotnet pack "BepuUtilities" -c Release
        dotnet nuget push "**/*.nupkg" -s "github" -k "${{secrets.GITHUB_TOKEN}}" --skip-duplicate
        dotnet nuget push "**/*.nupkg" -s "https://api.nuget.org/v3/index.json" -k "${{secrets.NUGET_KEY}}" --skip-duplicate